export const skills = [
  "NodeJS",
  "Typescript",
  "React",
  "Python",
  "YAML",
  "SQL",
  "MongoDB",
  "Prisma",
  "HTML",
  "CSS",
  "NextJS",
  "ExpressJS",
  "TailwindCSS",
  "AWS",
  "GitHub",
  "Vercel",
  "Harness",
  "Cypress",
  "Wordpress",
  "Docker",
  "Swagger",
  "Jenkins",
];

export const experiences = [
  {
    title: "Lead Software Engineer (Contractor)",
    company: "Rave3 NFT",
    image: "/r3.png",
    date: "January 2023 - July 2023",
  },
  {
    title: "Software Engineer - Applications",
    company: "Symbiont.io (Ceased Operations)",
    image: "/symbiont.png",
    date: "June 2022 - December 2022",
  },
  {
    title: "Software Engineer II",
    company: "The Beachbody Company",
    image: "/beachbody.png",
    date: "September 2020 - June 2022",
  },
  {
    title: "Software Engineer I",
    company: "The Beachbody Company",
    image: "/beachbody.png",
    date: "July 2019 - September 2020",
  },
];
